M48
; DRILL file {KiCad 9.0.6} date 2026-04-26T14:06:45-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-26T14:06:45-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X63.22Y-116.15
X63.22Y-141.48
X89.62Y-141.48
T2
X102.52Y-170.35
X166.08Y-100.1
M30
